config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :users, except: [:new] do
    collection do
      get "signup", to: "users#new"
    end
    member do
      get :following, :followers
    end
  end
  root 'microposts#index'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    has_one_attached :image do |attachable|
        attachable.variant :display, resize_to_limit: [500, 500]
    end
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 140}
    validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                     message: "must be a valid image format" },
                    size:         { less_than: 5.megabytes,
                                     message:   "should be less than 5MB" }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: %i[ create destroy ]
  before_action :correct_user, only: %i[destroy]
  # GET /microposts or /microposts.json
  def index
    if logged_in?
      @microposts = Micropost.all
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to root_url, notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        @feed_items = current_user.feed.paginate(page: params[:page])
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy

    respond_to do |format|
      flash[:success] = "Micropost was successfully destroyed."
      if request.referrer.nil? || request.referrer == microposts_url
        redirect_to root_url, status: :see_other
      else
        redirect_to request.referrer, status: :see_other
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :image)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url, status: :see_other if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id='micropost-<%= micropost.id %>'>
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class='user'><%= link_to micropost.user.name, micropost.user %></span>
  <span class='content'>
    <%= micropost.content %>
    <% if micropost.image.attached? %>
      <%= image_tag micropost.image.variant(:display) %>
    <% end %>
  </span>
  <span class='timestamp'>
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to 'delete', micropost, data: { 'turbo-method': :delete,
                                               turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </span>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, 'Editing Micropost')%>

<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<% provide(:title, "Microposts")%>

<% if logged_in? %>
  <div class='row'>
    <aside class='col-md-4'>
      <section class='user_info'>
        <%= render 'shared/user_info' %>
      </section>
      <section class='stats'>
         <%= render 'shared/stats' %>
      </section>
      <section class='micropost_form'>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class='col-md-8'>
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class='center jumbotron'>
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href='https://www.railstutorial.org/'>Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to 'Sign up now!', signup_users_path, class: 'btn btn-lg btn-primary' %>
  </div>

  <%= link_to image_tag('rails.svg', alt: 'Rails logo', width: '200'),
                        'https://rubyonrails.org/' %>
<% end %>

app/views/microposts/new.html.erb
<% provide(:title, 'New Micropost')%>

<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<% provide(:title, 'Show Micropost')%>

<p style="color: green"><%= notice %></p>

<%= render @micropost %>

<div>
  <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
  <%= link_to "Back to microposts", microposts_path %>

  <%= button_to "Destroy this micropost", @micropost, method: :delete %>
</div>